title       = "nominatim"
baseURL     = "https://nominatim-cli.tamnd.com/"
description = "A command line for nominatim."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/nominatim-cli"
